# -*- coding: utf-8 -*-
"""gdse60-MLWS-workbook-day-01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cz1CBtErfIEXwqcaSyjziK6pTaUhQih2
"""

!python --version

"""## variable

....
- how to use
-dict
-list
-tuple


## flow controller

- if
- else if
- while
- for

## ** oop

- funtion(method)
- class
- abstraction class
- interface
- overloding/override


"""

print("Hellow piyumal")

a=10
b=10.5
c="kamal"
print(a)
print(b)
print(c)

a=10
b=20
print(a+b)

a=10
b="5"
print(a+b)

a=10
b="5"
print(type(a))
print(type(b))

"""### area calculator

area=height*width
"""

height=10
width=20
area=height*width
print("Area is : ",area)

"""## method creation"""

def area_calculator(height,width):
  area=height*width
  print(area)

area_calculator(50,100)

class Students:  #class name start is capital
  print ("piyumal")

  def getAge():  #method name start is simpale
    print("24")

  getAge()  # camal case use

"""- if / elaseif / else"""

age=10;
if age>5:
  print("he is go to school");

def check_age(age):
  if age>5:
    print("he is go to school");
  else:
    print("he is go don't to school");

check_age(4)

def check_age(age):
  if age>7:
    print("grade 7");
  elif age>=6:
    print("grade 6");
  elif age>5:
    print("grade 5");
  else:
    print("he is go don't to school");

check_age(4)
check_age(6)

"""- # list"""

age_list=[10,20,30,40,50]
print(age_list)
print(type(age_list)) #list type

"""- # dict"""

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
print(type(thisdict)) #dict type

"""- # tuple"""

thistuple = ("apple", "banana", "cherry")
print(thistuple)
print(type(thistuple))

sum(age_list)  #pridifine method

for i in range(age_list):
  sum+=age_list

min(age_list)

max(age_list)

len(age_list)

rn=range(10)
print(rn)
print(type(rn))

list=(range(2))
print(list)

"""- # for loop"""

for eliment in age_list:
  print(eliment)

for i in range(10):
  print(i)

for i in range(len(age_list)):
  print(i)

for i in range(len(age_list)):
  print(age_list[i])

number=[2,9,1,4,3,2,6,5,4]

print(len(number))
for j in range(len(number)):
  for i in range(len(number)-1):
    if number[j]+number[i]>10:
     print(j,i)